apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  PORT: "3550"
  # DISABLE_TRACING: "1"
  # DISABLE_PROFILER: "1"
  # DISABLE_STATS: "1"
  # JAEGER_SERVICE_ADDR: "jaeger-collector:14268"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: productcatalog-service
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.2.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3550
        envFrom:
            - configMapRef:
                name: product-config
        readinessProbe:
          tcpSocket:
            port: 9555
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9555
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550

