apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  PORT: "3550"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: ProductCatlaog
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.2.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3550
        envFrom:
            - configMapRef:
                name: product-config
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  ports:
  - port: 3550
    targetPort: 3550
