apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
  namespace: default
data:
  PORT: "8080"
  # DISABLE_TRACING: "1"
  DISABLE_PROFILER: "1"
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: email-service
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.2.3
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"
        ports:
        - containerPort: 8080
        envFrom:
            - configMapRef:
                name: email-config
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20    
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: default
spec:
  selector:
    app: emailservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
