apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
data:
  PORT: "8080"
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: email service
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.2.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
            - configMapRef:
                name: email-config
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  selector:
    app: emailservice
  ports:
  - port: 8080
    targetPort: 8080
