apiVersion: v1
kind: ConfigMap
metadata:
  name: recom-config
data:
  PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend
spec:
  selector:
    matchLabels:
      app: recommend
  template:
    metadata:
      labels:
        app: recommend
    spec:
      containers:
        - name: recommend
          imagePullPolicy: Always
          image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.3
          envFrom:
            - configMapRef:
                name: recom-config
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: recommend
spec:
  selector:
    app: recommend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
