apiVersion: v1
kind: ConfigMap
metadata:
  name: recommend-config
data:
  PORT: "8080"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: recommendation-service
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        envFrom:
            - configMapRef:
                name: recommend-config   
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]            
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  selector:
    app: recommendationservice
  ports:
  - port: 8080
    targetPort: 8080