apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  PORT: "7070"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cart-service
        image: gcr.io/google-samples/microservices-demo/cartservice:v0.2.3
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"
        ports:
        - containerPort: 7070
        envFrom:
            - configMapRef:
                name: cart-config
        readinessProbe:
          tcpSocket:
            port: 7071
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  selector:
    app: cartservice
  ports:
  - name: grpc 
    port: 7070
    targetPort: 7070

