apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
 ingressClassName: nginx
 rules:
    - host: "foo.bar.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
          - path: "/crt"
            pathType: Prefix
            backend:
              service:
                name: cartservice
                port:
                  number: 7070
          - path: "/check"
            pathType: Prefix
            backend:
              service:
                name: checkoutservice
                port:
                  number: 5050
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: currencyservice
                port:
                  number: 7000
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: emailservice
                port:
                  number: 8080
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: paymentservice
                port:
                  number: 50051
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: productcatalogservice
                port:
                  number: 3550
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: recommendationservice
                port:
                  number: 8080
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: shippingservice 
                port:
                  number: 50051
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: adservice
                port:
                  number: 9555


