apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
data:
  PORT: "50051"
  # DISABLE_TRACING: "1"
  # DISABLE_PROFILER: "1"
  # DISABLE_STATS: "1"
  # JAEGER_SERVICE_ADDR: "jaeger-collector:14268"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shipping-service
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.3
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"
        ports:
        - containerPort: 50051
        envFrom:
            - configMapRef:
                name: shipping-config
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]        
        
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  selector:
    app: shippingservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051