apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
data:
  PORT: "5050"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  PAYMENT_SERVICE_ADDR: "paymentservice:50051"
  EMAIL_SERVICE_ADDR: "emailservice:5000"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"
  # DISABLE_TRACING: "1"
  # DISABLE_PROFILER: "1"
  # DISABLE_STATS: "1"
  # JAEGER_SERVICE_ADDR: "jaeger-collector:14268"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkout-service
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.3
        resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "250m"
        ports:
        - containerPort: 5050
        envFrom:
            - configMapRef:
                name: checkout-config
        readinessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 15
          periodSeconds: 20 
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  selector:
    app: checkoutservice
  ports:
   - name: grpc
     port: 5050
     targetPort: 5050

