apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  PORT: "50051"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: payment
        image: gcr.io/google-samples/microservices-demo/paymentservice
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
        envFrom:
            - configMapRef:
                name: payment-config
       
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  selector:
    app: paymentservice
  ports:
  - port: 50051
    targetPort: 50051
        
