apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  PORT: "50051"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: payment-service
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.2.3
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"
        ports:
        - containerPort: 50051
        envFrom:
            - configMapRef:
                name: payment-config
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]        
       
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051