apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
data:
  PORT: "50051"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: Shipping
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
       envFrom:
            - configMapRef:
                name: shipping-config
        
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  selector:
    app: shippingservice
  ports:
  - port: 50051
    targetPort: 50051
