apiVersion: v1
kind: ConfigMap
metadata:
  name: currency-config
data:
  PORT: "7000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currency-service
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.2.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7000
        envFrom:
            - configMapRef:
                name: currency-config
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  selector:
    app: currencyservice
  ports:
  - port: 7000
    targetPort: 7000

